//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRIBUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATRIBUTO()
        {
            this.ATRIBUTOPERMITIDO = new HashSet<ATRIBUTOPERMITIDO>();
        }
    
        public decimal CODIGOATRIBUTO { get; set; }
        public Nullable<decimal> CODIGOPRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATRIBUTOPERMITIDO> ATRIBUTOPERMITIDO { get; set; }
    }
}
