//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFUGURACION
    {
        public decimal CODIGOVALORESPERMITIDOS { get; set; }
        public decimal CODIGOLINEA { get; set; }
        public string CONFIGURACION { get; set; }
        public decimal CODIGOATRIBUTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal CODIGOPRODUCTO { get; set; }
        public decimal NUMFACTURA { get; set; }
    }
}
