//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUESTIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUESTIONARIO()
        {
            this.PREGUNTA = new HashSet<PREGUNTA>();
        }
    
        public decimal IDCUESTIONARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal IDCUESTIOARIO { get; set; }
        public decimal IDPREGUNTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
    }
}
