//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIMENSION
    {
        public decimal CODIGODIMENSION { get; set; }
        public string ANCHO { get; set; }
        public string LARGO { get; set; }
        public string VOLUMEN { get; set; }
        public string PROFUNDIDAD { get; set; }
        public decimal CODIGOPRODUCTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
