//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public decimal CODIGODIRECCION { get; set; }
        public Nullable<decimal> CODIGOCIUDAD { get; set; }
        public decimal NUMFACTURA { get; set; }
        public string IDCLIENTE { get; set; }
        public decimal CODDIRECCION { get; set; }
        public decimal CODCOMPRA { get; set; }
    }
}
