//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.LINEA = new HashSet<LINEA>();
        }
    
        public decimal NUMFACTURA { get; set; }
        public decimal CODIGOMONEDA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string IDCLIENTE { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
        public decimal CODCOMPRA { get; set; }
        public decimal CODDIRECCION { get; set; }
        public decimal CODIGOPRODUCTO { get; set; }
        public decimal CODIGODIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEA> LINEA { get; set; }
    }
}
