//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVPRODUCTO
    {
        public decimal IDPRODUCTO { get; set; }
        public decimal IDPROVEEDOR { get; set; }
        public string SERIE { get; set; }
        public Nullable<decimal> FACTURA { get; set; }
        public decimal CODIGOPROVEEDOR { get; set; }
    }
}
