//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTAPRECIO
    {
        public decimal CODIGOLISTAPRECIO { get; set; }
        public decimal IDCLIENTE { get; set; }
        public Nullable<decimal> IDPRODUCTO { get; set; }
        public string PRECIO { get; set; }
        public decimal CODIGOPRODUCTO { get; set; }
        public string IDCLIENTE1 { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
