//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoEntities1 : DbContext
    {
        public proyectoEntities1()
            : base("name=proyectoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATRIBUTO> ATRIBUTO { get; set; }
        public virtual DbSet<ATRIBUTOPERMITIDO> ATRIBUTOPERMITIDO { get; set; }
        public virtual DbSet<CARACTERISTICA> CARACTERISTICA { get; set; }
        public virtual DbSet<CARACTERISTICAPRODUCTO> CARACTERISTICAPRODUCTO { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CUESTIONARIO> CUESTIONARIO { get; set; }
        public virtual DbSet<DIMENSION> DIMENSION { get; set; }
        public virtual DbSet<DIRECCION> DIRECCION { get; set; }
        public virtual DbSet<DISTRITO> DISTRITO { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<INVPRODUCTO> INVPRODUCTO { get; set; }
        public virtual DbSet<LINEA> LINEA { get; set; }
        public virtual DbSet<LINEAPRODUCTO> LINEAPRODUCTO { get; set; }
        public virtual DbSet<LISTAPRECIO> LISTAPRECIO { get; set; }
        public virtual DbSet<MONEDA> MONEDA { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PREGUNTA> PREGUNTA { get; set; }
        public virtual DbSet<PREGUNTAPERMITIDA> PREGUNTAPERMITIDA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<RESPUESTACUESTIONARIO> RESPUESTACUESTIONARIO { get; set; }
        public virtual DbSet<SUBCARACTERISTICAS> SUBCARACTERISTICAS { get; set; }
        public virtual DbSet<TARJETA> TARJETA { get; set; }
        public virtual DbSet<CONFUGURACION> CONFUGURACION { get; set; }
        public virtual DbSet<NAVEGACION> NAVEGACION { get; set; }
    }
}
