//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVEGACION
    {
        public decimal CODIGOCLIENTE { get; set; }
        public decimal CODIGOSUBCARACTERISTICA { get; set; }
        public string SITIOVISITADO { get; set; }
        public string IDCLIENTE { get; set; }
        public decimal CODIGOSUBCARAC { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual SUBCARACTERISTICAS SUBCARACTERISTICAS { get; set; }
    }
}
