//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTAPERMITIDA
    {
        public decimal IDCUESTIONARIO { get; set; }
        public decimal IDPREGUNTA { get; set; }
        public string PREGUNTA { get; set; }
        public decimal IDRESPUESTACUESTIONARIO { get; set; }
        public decimal CODIGOLINEA { get; set; }
        public decimal CODIGORESPUESTAPERMITIDA { get; set; }
        public decimal IDCUESTIOARIO { get; set; }
    
        public virtual PREGUNTA PREGUNTA1 { get; set; }
        public virtual RESPUESTACUESTIONARIO RESPUESTACUESTIONARIO { get; set; }
    }
}
