//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREGUNTA()
        {
            this.PREGUNTAPERMITIDA = new HashSet<PREGUNTAPERMITIDA>();
        }
    
        public decimal IDCUESTIOARIO { get; set; }
        public decimal IDPREGUNTA { get; set; }
        public string PREGUNTA1 { get; set; }
        public decimal IDCUESTIONARIO { get; set; }
    
        public virtual CUESTIONARIO CUESTIONARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTAPERMITIDA> PREGUNTAPERMITIDA { get; set; }
    }
}
