//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.ATRIBUTO = new HashSet<ATRIBUTO>();
            this.CARACTERISTICAPRODUCTO = new HashSet<CARACTERISTICAPRODUCTO>();
            this.DIMENSION = new HashSet<DIMENSION>();
            this.LINEA = new HashSet<LINEA>();
            this.LISTAPRECIO = new HashSet<LISTAPRECIO>();
        }
    
        public decimal CODIGOPRODUCTO { get; set; }
        public Nullable<decimal> CODIGODIMENSION { get; set; }
        public Nullable<decimal> IDVERSION { get; set; }
        public string DESCRIPCION { get; set; }
        public string IMAGENHD { get; set; }
        public string IMAGEN { get; set; }
        public string PESO { get; set; }
        public decimal NUMFACTURA { get; set; }
        public decimal CODIGOCARACTPROD { get; set; }
        public decimal CODIGOLISTAPRECIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATRIBUTO> ATRIBUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARACTERISTICAPRODUCTO> CARACTERISTICAPRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIMENSION> DIMENSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEA> LINEA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTAPRECIO> LISTAPRECIO { get; set; }
    }
}
