//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSilverLight.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPUESTACUESTIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESPUESTACUESTIONARIO()
        {
            this.LINEA = new HashSet<LINEA>();
            this.PREGUNTAPERMITIDA = new HashSet<PREGUNTAPERMITIDA>();
        }
    
        public decimal CODIGOLINEA { get; set; }
        public decimal CODIGORESPUESTAPERMITIDA { get; set; }
        public string RESPUESTA { get; set; }
        public decimal IDCUESTIONARIO { get; set; }
        public decimal IDPREGUNTA { get; set; }
        public string PREGUNTA { get; set; }
        public decimal CODIGOPRODUCTO { get; set; }
        public decimal NUMFACTURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINEA> LINEA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTAPERMITIDA> PREGUNTAPERMITIDA { get; set; }
    }
}
